apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - repositories.yaml
  - signoz-helmrelease.yaml
  - otel-cilium-helmrelease.yaml
  - otel-cilium-rbac.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=helm/cilium/values.yaml
  - name: signoz-values
    files:
      - values.yaml=helm/signoz/values.yaml
  - name: otel-cilium-values
    files:
      - values.yaml=helm/opentelemetry-collector/values.yaml
