autoDirectNodeRoutes: true
bandwidthManager:
    enabled: true
bpf:
    clockProbe: true
    ctGlobalAnyMax: 131072
    ctGlobalTCPMax: 131072
    ctTcpTimeoutEstablished: 21600s
    lbExternalClusterIP: true
    mapDynamicSizeRatio: 0.005
    masquerade: true
    natMax: 196608
    neighMax: 196608
    policyMapMax: 16384
    preallocateMaps: true
cni:
    chainingMode: none
devices: eth0
directRoutingSkipUnreachable: true
endpointRoutes:
    enabled: true
envoy:
    config:
        concurrency: 4
externalIPs:
    enabled: true
hubble:
    enabled: true
    relay:
        enabled: true
    ui:
        enabled: false
ingressController:
    default: true
    enabled: true
    loadbalancerMode: shared
ipam:
    mode: multi-pool
    operator:
        autoCreateCiliumPodIPPools:
            default:
                ipv4:
                    cidrs:
                        - 10.201.1.0/24
                    maskSize: 32
ipv4NativeRoutingCIDR: 10.201.0.0/21
k8sServiceHost: tstb1.cluster.local
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
    leaseDuration: 30s
    leaseRenewDeadline: 10s
    leaseRetryPeriod: 2s
l2podAnnouncements:
    enabled: true
loadBalancer:
    acceleration: native
    algorithm: maglev
    enabled: true
    mode: dsr
nodePort:
    directRoutingDevice: eth0
    enabled: true
operator:
    replicas: 3
prometheus:
    enabled: true
resources:
    limits:
        cpu: 3000m
        memory: 2Gi
    requests:
        cpu: 1500m
        memory: 2Gi
routingMode: native
socketLB:
    enabled: true
    hostNamespaceOnly: true