socketLB:
  hostNamespaceOnly: true

ipam:
  mode: kubernetes

bpf:
  hostLegacyRouting: true

dnsProxy:
  minTtl: 300

hubble:
  export:
    static:
      enabled: true
      filePath: /var/run/cilium/hubble/events
  relay:
    enabled: true
  ui:
    enabled: true

encryption:
  enabled: true
  nodeEncryption: true
  type: wireguard

hostFirewall:
  enabled: true

policyEnforcementMode: default

extraConfig:
  allow-localhost: policy

kubeProxyReplacement: true

policyAuditMode: false

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445